NewProject/Models/NeededItem.cs
namespace NewProject.Models
{
    public class NeededItem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }
        public string? Type { get; set; }
        public int InitialPrice {  get; set; }
        public int TenderId {  get; set; }
        public Tender Tender { get; set; }
    }
}

NewProject/Controllers/CommitteeController.cs
namespace NewProject.Controllers
{
    public class CommitteeController : Controller
    {
        private readonly IMemberService _memberService;
        private readonly ITendersService _TendersService;
        private readonly ICommitteeService _committeeService;
       public CommitteeController(IMemberService memberService, ICommitteeService committeeService , ITendersService tendersService)
        {
            _memberService = memberService;
            _committeeService = committeeService;
            _TendersService = tendersService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult LastSLCMembers()
        {
            var slc = _committeeService.GetBySelectionCommitteeId();
            return View(slc);
        }
        public IActionResult LastSPCMembers()
        {
            var SPC = _committeeService.GetBySpecifictionCommitteeID();
            return View(SPC);
        }
        public IActionResult LastTECMembers()
        {
            var TEC = _committeeService.GetByTechnicalCommitteeId();
            return View(TEC);
        }
        public IActionResult DeterminCommitteeMembers()
        {
            CommitteeViewModel viewModel = new CommitteeViewModel();
            viewModel.Memebers = _memberService.GetMembers();
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeterminCommitteeMembers(CommitteeViewModel model)
        {
            if(!ModelState.IsValid)
            {
                CommitteeViewModel viewModel = new CommitteeViewModel();
                viewModel.Memebers = _memberService.GetMembers();
                return View(viewModel);
            }
            await _committeeService.AddCommitteeMembers(model);
            return RedirectToAction("index" , "Home");
        }
    }
    
}

NewProject/Controllers/NeededItemController.cs
namespace NewProject.Controllers
{
    public class NeededItemController : Controller
    {
        private readonly INeededItemService _neededItemService;
        public NeededItemController(INeededItemService neededItemService)
        {
            _neededItemService = neededItemService;
        }
        public IActionResult Index()
        {
            return View(_neededItemService.GetAllLast());
        }
        public IActionResult AddNeededItem()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNeededItem(NeededItemViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await _neededItemService.AddNeededItem(model);
            return RedirectToAction("AddNeededItem");
        }

        //for add Specification and price to Tender's Item
        public IActionResult Edit(int id)
        {
            var Item = _neededItemService.GetById(id);
            if (Item == null)
                return BadRequest();
            SpecificationNeededItemViewModel p = new SpecificationNeededItemViewModel();
            p.tenderId = Item.TenderId;
            p.id = Item.Id;
            p.Description = Item.Description;
            p.Type = Item.Type;
            p.Name = Item.Name;
            p.InitialPrice= Item.InitialPrice;         
            return View(p);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SpecificationNeededItemViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var n = _neededItemService.Edit(model);
            if (n == null)
                return BadRequest();
            //to go back for needed item and add sp.... and price for ather item
            return RedirectToAction(nameof(Index));
        }


    }
}

NewProject/Views/NeededItem/AddNeededItem.cshtml
@model NewProject.ViewModel.NeededItemViewModel

@{
    ViewData["Title"] = "AddNeededItem";
}
<div class="container-fluid d-flex align-items-start justify-content-center vh-100 mt-10">
    <div class="text-center">
        <h2>Enter Needed Items </h2>
        <hr />
        <div class="row">
            <div class="col-md-12">
                <form asp-action="AddNeededItem">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group ">
                      @*   <label asp-for="Name" class="control-label"></label> *@
                        <input asp-for="Name" class="form-control" placeholder="Record New Item" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group d-grid gap-2 space">
                        <input type="submit" value="Add ITem" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
        <br />
        <div class="form-group d-grid gap-2 space">

            <a asp-action="DeterminCommitteeMembers" asp-controller="Committee" class="btn btn-success mt-2"> Done </a>

        </div>
    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NewProject/Views/NeededItem/Edit.cshtml
@model SpecificationNeededItemViewModel

@{
    ViewData["Title"] = "Edit";
}
<div class="container-fluid d-flex align-items-start justify-content-center vh-100">
    <div class="text-center">
        <h4>Determine Specification and Price For each Item</h4>
        <hr />
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Edit" asp-controller="NeededItem" asp-route-id="@Model.id">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="tenderId" class="control-label"></label>
                        <input asp-for="tenderId" class="form-control" readonly />
                        <span asp-validation-for="tenderId" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" readonly />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" placeholder="Description"/>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="Type" class="control-label"></label>
                        <input asp-for="Type" class="form-control" placeholder="TYPE"/>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <br />
                    <div class="form-group">
                        <label asp-for="InitialPrice" class="control-label"></label>
                        <input asp-for="InitialPrice" class="form-control"/>
                        <span asp-validation-for="InitialPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group mt-4 d-grid gap-2">
                        <input type="submit" value="SAVE" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="~/js/pricevalidtion.js"></script>
}

NewProject/Views/NeededItem/Index.cshtml
@model IEnumerable<NewProject.Models.NeededItem>

@{
    ViewData["Title"] = "Index";
}


<div class="container-fluid d-flex align-items-start justify-content-center vh-100">
    <div class="text-center">
        <h1>Determine Specification and price for  Item</h1>
        <br />
        <div class="row">
            <div class="col-md-12">
                @* <p>
                <a asp-action="Create">Create New</a>
                </p> *@
                <table class="table table-bordered">
                    <thead>
                        <tr class="table-primary">
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TenderId)
                            </th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenderId)
                                </td>
                                <td>
                                    @* DSCNI => Determine Specification and price for  Item *@
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-secondary" style="color:black"> DSCNI </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>