NewProject/Controllers/CommitteeController.cs
namespace NewProject.Controllers
{
    public class CommitteeController : Controller
    {
        private readonly IMemberService _memberService;
        private readonly ITendersService _TendersService;
        private readonly ICommitteeService _committeeService;
       public CommitteeController(IMemberService memberService, ICommitteeService committeeService , ITendersService tendersService)
        {
            _memberService = memberService;
            _committeeService = committeeService;
            _TendersService = tendersService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult LastSLCMembers()
        {
            var slc = _committeeService.GetBySelectionCommitteeId();
            return View(slc);
        }
        public IActionResult LastSPCMembers()
        {
            var SPC = _committeeService.GetBySpecifictionCommitteeID();
            return View(SPC);
        }
        public IActionResult LastTECMembers()
        {
            var TEC = _committeeService.GetByTechnicalCommitteeId();
            return View(TEC);
        }
        public IActionResult DeterminCommitteeMembers()
        {
            CommitteeViewModel viewModel = new CommitteeViewModel();
            viewModel.Memebers = _memberService.GetMembers();
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeterminCommitteeMembers(CommitteeViewModel model)
        {
            if(!ModelState.IsValid)
            {
                CommitteeViewModel viewModel = new CommitteeViewModel();
                viewModel.Memebers = _memberService.GetMembers();
                return View(viewModel);
            }
            await _committeeService.AddCommitteeMembers(model);
            return RedirectToAction("index" , "Home");
        }
    }
    
}

NewProject/Controllers/OfferController.cs
namespace NewProject.Controllers
{
    public class OfferController : Controller
    {
        private readonly IValidItemService _validItemService;
        private readonly IVendorService _vendorService;
        private readonly IOfferService _offerService;
        private readonly INeededItemService _neededItemService;
        public OfferController(IValidItemService validItemService , IVendorService vendorService 
            , IOfferService offerService , INeededItemService neededItemService)
        {
            _validItemService = validItemService;
            _vendorService = vendorService;
            _offerService = offerService;
            _neededItemService = neededItemService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Add() 
        {
            OfferViewModel model = new OfferViewModel();
            model.Vendors = _vendorService.GetVendors();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(OfferViewModel model)
        { 
            if (!ModelState.IsValid)
            {
                return View(model);
            }
             _offerService.Add(model);

            return RedirectToAction("Items");
            
        }
        public IActionResult Items() //to show item that sended to vendors 
        {
            IEnumerable<NeededItem> NeededItems = _neededItemService.GetAllLast();
            IEnumerable<ValidItem> ListNeeded = _validItemService.ValidItems();
            List<NeededItem> NI = new List<NeededItem>();
            foreach (NeededItem neededItem in NeededItems)
            {
                var n = neededItem.Id;
                foreach (var valid in ListNeeded)
                {
                    var v = valid.NeededItemId;
                    if (n == v)
                    {
                        NI.Add(neededItem);
                    }
                }
            }
            return View(NI);
        } 
    }
}

NewProject/Controllers/TenderController.cs
namespace NewProject.Controllers
{
    public class TenderController : Controller
    {
        private readonly ITendersService _tendersService;
       
        public TenderController (ITendersService tendersService )
        {
            _tendersService = tendersService;
        }
        public IActionResult ShowTender()
        {
            return View(_tendersService.GetAll());
        }
        public IActionResult CreateTender()
        {
          
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateTender(TenderViewModel model)
        {
            if(!ModelState.IsValid)
            {
               
                return View(model);
            }
            await _tendersService.AddTender(model);
            return RedirectToAction("AddNeededItem" , "NeededItem");
        }
    }
}

NewProject/Controllers/ValidItemController.cs
namespace NewProject.Controllers
{
    public class ValidItemController : Controller
    {
        private readonly INeededItemService _neededItemService;
        private readonly IValidItemService _validItemService;
        public ValidItemController(INeededItemService neededItemService , IValidItemService validItemService)
        {
            _neededItemService = neededItemService;
            _validItemService = validItemService;
        }

        public IActionResult Index()
        {
            IEnumerable<NeededItem> NeededItems = _neededItemService.GetAllLast();
            IEnumerable<ValidItem> ListNeeded = _validItemService.ValidItems();
            List<NeededItem> NI  = new List<NeededItem>();
            foreach (NeededItem neededItem in NeededItems)
            {
                var n = neededItem.Id;
                foreach(var valid in ListNeeded)
                {
                    var v = valid.NeededItemId;
                    if(n == v)
                    {
                        NI.Add(neededItem);
                    }
                }
            }
            return View(NI);
        }
        public IActionResult ChooseValidItem() 
        {
            var items = _neededItemService.GetAllLast();
            return View(items);
        }
      //  [HttpPost]
        public async Task<IActionResult> Add(int Id) 
        {
            var item = _neededItemService.GetById(Id);
            if (item == null)
                return BadRequest();
            IEnumerable<ValidItem> ListNeeded = _validItemService.ValidItems();
            foreach (var i in ListNeeded)
            {
                if (i.NeededItemId == item.Id)
                {
                    return Content("This item is alredy added");
                }
            }
            await _validItemService.ValidItem(Id);
            return RedirectToAction("Index");
        }
    }
}

NewProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Graduation Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/bootstrap.min (4).css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/NewProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DLS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="">
                    <ul class="navbar-nav me-auto my-2 my-lg-0" style="--bs-scroll-height: 100px;">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Tender
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tender"
                                        asp-action="CreateTender">Create Tender</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tender"
                                        asp-action="ShowTender">Show Tender</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Item
                            </a>
                            <ul class="dropdown-menu gap-2">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ValidItem"
                                        asp-action="ChooseValidItem"> choose Valid Item </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="ValidItem"
                                        asp-action="index">Valid Item</a>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NeededItem"
                                asp-action="index">DeterminSP&PR</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Committee"
                                asp-action="index">Committee Members</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Offer"
                                asp-action="Add">AddOffer</a>
                        </li>
                        
                    </ul>
                    <form class="d-flex justify-content-center align-items-center gap-2" role="search">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-person-fill" viewBox="0 0 16 16">
                            <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6" />
                        </svg>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd"
                                    d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z" />
                                <path fill-rule="evenodd"
                                    d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z" />
                            </svg>
                    </form>
                </div>
                
            </div>
        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NewProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>