NewProject/Models/Offer.cs
namespace NewProject.Models
{
    public class Offer
    {
        public int id { get; set; }
        public int VendorId { get; set; }
        public Vendor Vendor { get; set; } 
        public ICollection<ValidItemOffer> ValidItems { get; set; }
        public ICollection<StepnItem> StepnItems { get; set; }
    }

}

NewProject/Controllers/OfferController.cs
namespace NewProject.Controllers
{
    public class OfferController : Controller
    {
        private readonly IValidItemService _validItemService;
        private readonly IVendorService _vendorService;
        private readonly IOfferService _offerService;
        private readonly INeededItemService _neededItemService;
        public OfferController(IValidItemService validItemService , IVendorService vendorService 
            , IOfferService offerService , INeededItemService neededItemService)
        {
            _validItemService = validItemService;
            _vendorService = vendorService;
            _offerService = offerService;
            _neededItemService = neededItemService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Add() 
        {
            OfferViewModel model = new OfferViewModel();
            model.Vendors = _vendorService.GetVendors();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(OfferViewModel model)
        { 
            if (!ModelState.IsValid)
            {
                return View(model);
            }
             _offerService.Add(model);

            return RedirectToAction("Items");
            
        }
        public IActionResult Items() //to show item that sended to vendors 
        {
            IEnumerable<NeededItem> NeededItems = _neededItemService.GetAllLast();
            IEnumerable<ValidItem> ListNeeded = _validItemService.ValidItems();
            List<NeededItem> NI = new List<NeededItem>();
            foreach (NeededItem neededItem in NeededItems)
            {
                var n = neededItem.Id;
                foreach (var valid in ListNeeded)
                {
                    var v = valid.NeededItemId;
                    if (n == v)
                    {
                        NI.Add(neededItem);
                    }
                }
            }
            return View(NI);
        } 
    }
}

NewProject/Controllers/StepnItemController.cs
using Microsoft.AspNetCore.Mvc;

namespace NewProject.Controllers
{
    public class StepnItemController : Controller
    {
        private readonly IOfferService _offerService;
        private readonly IValidItemService _validItemService;
        private readonly IAlternativeItemService _alternativeItemService;
        public StepnItemController(IOfferService offerService, IValidItemService validItemService, IAlternativeItemService alternativeItemService)
        {
            _offerService = offerService;
            _validItemService = validItemService;
            _alternativeItemService = alternativeItemService;
        }

        public IActionResult Index()
        {
            return View();
        } //not used yet
        public IActionResult AddAlternativeItems(int id)                                //id => for needed item 
        {
            var Lastoffer = _offerService.LastOffer();                                  //var LOID = Lastoffer!.id;
            var currentitem = _validItemService.GetValiditemByneededitemid(id);         // var CI = currentitem.id;

            AlternativeItemViewModel AVM = new AlternativeItemViewModel();
            IEnumerable<ValidItemOffer> VIOO = _offerService.AllValidItemOfer();
            // عشان يسجل العنصر دا مع العرض لو كان متسجلش
            foreach (var i in VIOO)
            {
                if (i.OfferId == Lastoffer!.id && i.ValidItemId == currentitem!.id)
                {
                    AVM.ValidItemId = currentitem!.id;
                    AVM.OfferId = Lastoffer.id;
                    return View(AVM);
                }
            }
            AVM.ValidItemId = currentitem!.id;
            AVM.OfferId = Lastoffer!.id;
            _offerService.AddVIO(id);
            return View(AVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddAlternativeItems(AlternativeItemViewModel SI)
        {

            if (!ModelState.IsValid)
            {
                return View(SI);
            }
            _alternativeItemService.Add(SI);
            AlternativeItemViewModel STI = new()
            {
                ValidItemId = SI.ValidItemId,
                OfferId = SI.OfferId,
            };
            return RedirectToAction("AddAlternativeItems" , STI);
        }
    }
}

NewProject/Views/Offer/Add.cshtml
@model OfferViewModel

@{
    ViewData["Title"] = "Add";
}

<div class="row  d-flex align-items-start justify-content-center vh-100">
    <div class="col-md-4">
        <h4> Add Offer </h4>
        <br />
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group space">
                <label asp-for="VendorId" class="control-label"></label>
                <select asp-for="VendorId" class="form-control" asp-items="@Model.Vendors">
                    <option value="">select Vendor</option>
                </select>
                <span asp-validation-for="VendorId" class="text-danger"></span>
            </div>
            <div class="form-group d-grid gap-2 space">
                <input type="submit" value="Create" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NewProject/Views/Offer/Items.cshtml
@model IEnumerable<NewProject.Models.NeededItem>

@{
    ViewData["Title"] = "Items";
}
<div class="container-fluid d-flex align-items-start justify-content-center vh-100">
    <div class="text-center">
        <h1>Items</h1>
        <br />
        <div class="row">
            <div class="col-md-12">

                <table class="table table-bordered">
                    <thead>
                        <tr class="table-primary">
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Type)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <a class="text-decoration-none btn text-bg-success" asp-action="AddAlternativeItems" asp-route-id="@item.Id" asp-controller="StepnItem"> @Html.DisplayFor(modelItem => item.Name)</a>
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Type)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>